env:
  global:
    secure: HL27Pwc/zT5QF3f7rT4GkFCbOoX9kzUdltz12S4oBqFX+EVnZRgjYlfwbC10YECK+6Mv+Xuwui9X8rl1rNVTV/dhvOnkF/2gl8/EX/GAozEbJ5ZFoIhJjp5kHVxAdykRMzhwFrMcvDZfzFHR1vvyC1QlYjmsQIhh8xu9Oo3fGq/wQ6qrDeDScJP1Ath36jptUWOGaTRDiW1UDuNZGvSB6dipSxMKh2QWE+BWA74QUjxm7UXbircylcwTbphKAo4y+9BnOFJVwYQlhcpNNSoGEWGyIGOqyyHslerPJ1e3QVM12xFOd8FnlgmHxS0DjbIcAwx4/0PRE6LNBU2tw9CtgL8+843P9o9XKWXSif3CDLkxyH9dJQ2SwChk4vNMxy98BmvVvhSc77LC/qkyCLBMuhTtLpdYoobk4BNUUXDe72scVQ33zHxTTGW27alW+UgoMWixA1cow61vCeHDNXsC2ISmR2rIg/YA+k8VsyPg4AqRuOC1Qr8o3k8VZeiDmxJZTVZ09z3p0EYxuLy0PlIlwVsWEhguhskzIN4jmDMSSoYgwvrNNqFFprF1LScIZTbnkS/DZwC1agSbCPkWGdDaWdIdBzvjJ5BxcSFpGXU9q5b/yAx6urR9fQzH0ECXRGIeHOA3Hyl7XDTos7zYuyD51AYSRbi+O6fKfXYhIHyAHEc=

language: node_js

node_js:
- node

before_install:
- npm install -g npm

install:
- npm install

cache:
  directories:
  - node_modules

notifications:
  email:
    recipients:
    - sdrsn.chaki@gmail.com
    on_success: always
    on_failure: always

after_success:
- |
  .travis/set-up-ssh --key "$encrypted_3f698a17050f_key" \
                        --iv "$encrypted_3f698a17050f_iv" \
                        --path-encrypted-key ".travis/github_deploy_key.enc"
