language: node_js
node_js:
  - node
before_install:
  - npm install -g npm
install:
  - npm install
  #- npm start
cache:
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - sdrsn.chaki@gmail.com
    on_success: always
    on_failure: always
  slack:
    rooms:
      - upskillable:NFfjbRNQAqsp6Yw6EHToWMgC#devops
    on_success: always
    on_failure: always
